// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbBCE55geQhBvLL8hnk77IZ1CTkbwoUEI',
    appId: '1:256030069799:web:8c3bfebea7baf9de3f2a02',
    messagingSenderId: '256030069799',
    projectId: 'fuelfire-65699',
    authDomain: 'fuelfire-65699.firebaseapp.com',
    storageBucket: 'fuelfire-65699.appspot.com',
    measurementId: 'G-CYBN9VC35B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJCxcGUBmbQcO7hG6XqqZBSnHJ9EV0lTQ',
    appId: '1:256030069799:android:4e14b37ed4fd10373f2a02',
    messagingSenderId: '256030069799',
    projectId: 'fuelfire-65699',
    storageBucket: 'fuelfire-65699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDr3C6SIFIB5vm9hvhj5ZV8HK2CnIyAmY',
    appId: '1:256030069799:ios:0b089e73f427db6a3f2a02',
    messagingSenderId: '256030069799',
    projectId: 'fuelfire-65699',
    storageBucket: 'fuelfire-65699.appspot.com',
    iosBundleId: 'com.example.fuelfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDr3C6SIFIB5vm9hvhj5ZV8HK2CnIyAmY',
    appId: '1:256030069799:ios:c498251033edce5f3f2a02',
    messagingSenderId: '256030069799',
    projectId: 'fuelfire-65699',
    storageBucket: 'fuelfire-65699.appspot.com',
    iosBundleId: 'com.example.fuelfire.RunnerTests',
  );
}
